### ISSUE TITLE
Open to site overhaul?

### ISSUE THREAD

**Issue by chopfitzroy** [LightTable/lighttable.com#16]
Hey I really like light table and I feel the site does not do the editor justice, I would be happy to overhaul the site, but I am a pretty useless designer would any body be interested in collaborating on a new site, if it is even wanted?

Cheers.

**Comment by sbauer322** [comment]
Hi @CrashyBang!

Just noticed this issue - sorry for the delayed response! I think updates to the the site would be welcomed by all. However, regarding an overhaul, I am not currently aware of a designer to pair you up with.

So I guess that leaves us in a frustrating position of being open to the help but not being able to provide adequate help to you in terms of design. That said, we are happy to look at any effort you can send our way.

A question I have for you, @CrashyBang, would be: what, in particular, do you feel should be updated? Perhaps changes could be done incrementally.

**Comment by chopfitzroy** [comment]
Hey @sbauer322,

Well the source/docs/discussion/blog are all handled individually either by an external service or a module so I guess what I am referring to more than anything is the home page.

The look and feel is _outdated_ I think it would be nice to make this more modern potentially _flat_ design. A content restructure might also help, I don't feel the current bullet points really convey the awesomeness of lighttable.

Thoughts?
Cheers.

**Comment by sbauer322** [comment]
I do feel the homepage seems stuck in time and is not holding up to fresher relevant sites. For comparison, the following all feel a bit nicer, or unique in a good way:
- [Clojure](https://clojure.org/) 
- [Clojurescript](http://clojurescript.org/)
- [Cursive](https://cursive-ide.com/)
- [Atom](https://atom.io/)
- [ReactOS](http://www.reactos.org/)

Seems like a flat design is worth investigating as well as updating the bullet points. That said, I'm not sure what it should look like instead as I am not knowledgeable enough about web design to objectively say "this is good" or "this is a well designed site"... it would mostly fall to personal or visual preference at this point.

As mentioned previously, happy to look at any changes or suggestions (both big and small). So, in short, feel free to make changes and see what comes out of it? 

I wish I had more solid thoughts to better help you!

**Comment by chopfitzroy** [comment]
Hey @sbauer322,

I know what you mean design is not my strong point either, I think Atom would be a good starting point, I will look into this when I have the time since logging this issue my schedule has somewhat exploded :).

Cheers.

**Comment by sbauer322** [comment]
No worries - chances are the homepage will be in the same state then too :grinning:

With any luck, we can come up with some ideas we want implemented by then.

Sorry again for getting back to you so late!

**Comment by sbauer322** [comment]
Closing this issue for now. Will reopen when @CrashyBang or anyone else interested is available.
