### ISSUE TITLE
Who is in control of the domain name lighttable.com, its web analytics, and twitter handle?

### ISSUE THREAD

**Issue by sbauer322** [LightTable/lighttable.com#21]
Apologies in advance if this is something that should be obvious, but I didn't see it anywhere. 

Since I can't find any info about this I assume it has never come up, or was discussed in private channels... which is fine, but as people stop contributing or depart the project we waste time asking the same questions. 
#### Domain name

Semi important, as running `whois lighttable.com` suggests the domain name will be expiring relatively soon with this line: `Registrar Registration Expiration Date: 2016-12-18T05:00:00.00Z`

As the project and site were moved to be community managed it is important to determine who is the point of contact for the domain name (and similarly who is paying for it).
#### Web Analytics

While on the topic, who is getting access to all of the Light Table site's data? Ghostery suggests there are four trackers:
- DoubleClick
- Google Analytics
- Twitter Button
- Twitter Syndication

Of concern is the Google Analytics and DoubleClick. Are these simply something Github Pages inject and we have no access to?
#### Twitter Handle

There has been no real twitter activity from [@LightTable](https://twitter.com/lighttable) for months. In order to maintain a social media presence it would be prudent to keep it active... yes, I know we have not had a release for longer, but there is still work happening and ways to stay relevant using it.

Knowing the point of contact for the twitter handle, or allowing access to it via the LightTable organization's roles and permissions, would be beneficial... not sure if the latter is a thing that exists.
#### Guesses

I suppose these questions are irrelevant if Chris is still the owner of LightTable organization, as it would then be obvious, but who is the owner or lead maintainer is not clear at this point either.

My guess is either @ibdknox or @cldwalker... clarification about this topic is desired, please! Feel free to contact me via alternate methods if you prefer to keep it discrete.

**Comment by ibdknox** [comment]
I own the domains. They're set to auto-renew.

**Comment by sbauer322** [comment]
Thanks for the info, @ibdknox, I had figured as much but wanted to confirm... Do you mind if I mention this in a wiki page for posterity?

Or maybe there is a way to display this info privately within the organization?

**Comment by ibdknox** [comment]
Sure.

**Comment by sbauer322** [comment]
Sorry to continue asking questions, @ibdknox, I know you are busy, but would you know about the Twitter handle or Web Analytics as well?

**Comment by kenny-evitt** [comment]
@sbauer322 Chris shared with Gabriel, Magnus, and I the Twitter account credentials. Based on an email thread between 2015-12-12 and 2016-01-22, Chris should have added Gabriel to the Light Table "property" in Google Analytics, tho based on that conversation the property (the GA endpoint that LT uses) is still under Chris's personal Google Analytics account. Gabriel apparently added both Magnus and I to the property as I'm looking at the LT data in Google Analytics as I type.

I've only briefly looked in Google Analytics – I'm completely unfamiliar with it – and it looks like we've got a "Light Table" account setup but the only property we have is "LightTable.com". I would guess that's just for the website. I know there's some kind of 'metrics' or 'analytics' for the LT app itself, but I'm guessing now that that doesn't use GA.

**Comment by ibdknox** [comment]
Yeah, I added Kenny, Gabriel, and Magnus to GA a while back. I believe you guys have rights to add others as well.

The old metrics stuff is all turned off, I left the end points up so that things don't go crazy for people running older versions of LT that really relied on it for version checks and such.

**Comment by sbauer322** [comment]
Thanks everyone, I've added this information to the LightTable wiki [here](https://github.com/LightTable/LightTable/wiki/For-Contributors).

Closing as all questions have been addressed.
