### ISSUE TITLE
No HTTPS

### ISSUE THREAD

**Issue by dividedmind** [LightTable/lighttable.com#5]
The page is not available in HTTPS, yet it offers binaries for me to download, install and run on my machine. Since there is no way I can verify the authenticity of those binaries they're inherently untrusted, even if I'm willing trust lighttable developers. (The binaries themselves are served over HTTPS from cloudfront, yes, but someone could easily MITM me and substitute their malicious builds.)

**Comment by dividedmind** [comment]
(I just noticed I can copy the links from this repo. But still the default way is plain HTTP.)

**Comment by cldwalker** [comment]
We use Github Pages  which doesn't support ssl for custom domains - see https://github.com/isaacs/github/issues/156 . Until it does, we could add a section to the readme which points to the https:// links we have on cloudfront

**Comment by cldwalker** [comment]
Closing as latest 0.8.0 include checksums for downloads - https://github.com/LightTable/LightTable/releases/tag/0.8.0
